---
version: "2.1"
services:
  gotify:
    image: gotify/server-arm7
    container_name: gotify
    networks: 
      - swagnet
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      # - GOTIFY_DEFAULTUSER_PASS=custom
    volumes:
      - /home/max/docker-containers-conf/gotify:/app/data
    ports:
      - 8081:80
    restart: unless-stopped
networks:
  swagnet:
    external: true